### ISSUE TITLE
Learn IDE crashes when merging without comment

### ISSUE THREAD

**Issue by tsengsational** [learn-co-curriculum/git-merge-conflicts#10]
Hi, I noticed that whenever I try to merge branches in Learn without commenting, I get an error which eventually crashes Learn IDE. It might be good to instruct students to be sure to add a comment whenever they merge like:

git merge doc-brown -m "merge doc-brown"

thanks!

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
