### ISSUE TITLE
Update for Step 3 in readme

### ISSUE THREAD

**Issue by joanrig** [learn-co-curriculum/git-merge-conflicts#11]
Instructions are: 

---- 
Step 3: Merge!
You're going to add both the doc-brown branch and the marty-mcfly branch to the master branch using merge. Merge the doc-brown branch first by running 
git merge doc-brown 
in the terminal.

---
this produces an error message - you are prompted to enter a message related to the merge - and you are sent to a new screen that has a totally different interface ...
solution is to run merge command like this:
git merge doc-brown -m "merging doc brown/ etc"

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
